name: Deployment pipeline 

on: 
    push:
        branches: 
            - main

jobs: 
    simple_Deployment_pipeline:
      if: ${{github.event_name == 'push'}}
      run-on: ubuntu-20.04
      steps: 
        - uses: actions/checkout@v4
        - uses: actions/setup-node@4
         with: 
            node-version: '20'
        - name: Insatla dependencias
          run: npm install
        - name: Checkear el estilo del codigo
          run: npm run eslint
        - name: test
          run: npm run test 